server:
  port: 7071
  servlet:
    context-path: /web

eureka:
  instance:
    lease-renewal-interval-in-seconds: 60
    lease-expiration-duration-in-seconds: 120
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: web-service


auth-server: http://localhost:7070/auth # sso-server地址
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      user-info-uri: ${auth-server}/user
      prefer-token-info: false
      jwt:
        key-uri: ${auth-server}/oauth/token_key