server:
  port: 8081
  servlet:
    context-path: /auth
    session:
      timeout: 600

security:
  oauth2:
    client:
      client-id: bla
      client-secret: blubb

spring:
  application:
    name: auth-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/