server:
  port: 8081
  servlet:
    session:
      timeout: 600

spring:
  application:
    name: auth-server
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


facebook:
  clientId: 467525726975630
  clientSecret: a7b56ef0799b916d6530cb13d5fe8b1c

security:
  oauth2:
    client:
      client-id: bla
      client-secret: blubb