server:
  port: 8081

spring:
  application:
    name: zuul-service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 60 #每间隔60s，向服务端发送一次心跳，证明自己依然"存活"
    lease-expiration-duration-in-seconds: 120 #告诉服务端，如果我120s之内没有给你发心跳，就代表我"死"了，将我踢出掉。
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#auth-server: http://localhost:7070/auth # sso-server地址
#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      access-token-uri: ${auth-server}/oauth/token
#      user-authorization-uri: ${auth-server}/oauth/authorize
#    resource:
#      user-info-uri: ${auth-server}/user
#      prefer-token-info: false
#      jwt:
#        key-uri: ${auth-server}/oauth/token_key

zuul:
  ignoredServices: '*' #忽略所有微服务，只路由指定微服务
  add-host-header: true #重定向问题
  routes:
    auth-service:
      path: /auth/**
      stripPrefix: false
      serviceId: auth-service
      sensitive-headers:
    web-service:
      path: /web/**
      stripPrefix: false
      serviceId: web-service
      sensitive-headers: